services:
  postgres:
    image: postgres:18-alpine
    container_name: db_flowershop
    restart: unless-stopped

    env_file:
      - ../.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/db_flowershop

volumes:
  postgres_data:
